/** Formulation des CGV et de la FAQ, sans les mots de l’article 50. */
export const VIRTUAL_ADVISOR_DISCLOSURE =
  'Les conseillers Callastral sont des voix et des personas virtuels créés par Callastral.';

/**
 * Article 50 du règlement européen sur l’IA, applicable depuis le 2 août 2026.
 * Seules ces lignes peuvent dire « intelligence artificielle » ou « AI ».
 */
export const AI_ACT_LINE = {
  fr: 'Conseiller virtuel Callastral — voix générée par intelligence artificielle',
  en: 'Callastral virtual advisor — AI-generated voice',
  es: 'Consejero virtual de Callastral — voz generada por inteligencia artificial',
  de: 'Virtueller Callastral-Berater — Stimme durch künstliche Intelligenz erzeugt',
  it: 'Consulente virtuale Callastral — voce generata dall’intelligenza artificiale',
} as const;

/** Même mention, accordée au féminin pour les conseillères. */
export const AI_ACT_LINE_FEMININE = {
  fr: 'Conseillère virtuelle Callastral — voix générée par intelligence artificielle',
  en: 'Callastral virtual advisor — AI-generated voice',
  es: 'Consejera virtual de Callastral — voz generada por inteligencia artificial',
  de: 'Virtuelle Callastral-Beraterin — Stimme durch künstliche Intelligenz erzeugt',
  it: 'Consulente virtuale Callastral — voce generata dall’intelligenza artificiale',
} as const;

export function aiActLine(locale: keyof typeof AI_ACT_LINE, gender?: 'femme' | 'homme' | null): string {
  return gender === 'femme' ? AI_ACT_LINE_FEMININE[locale] : AI_ACT_LINE[locale];
}

/** Phrase dite en ouverture d’appel, dans la langue du conseiller. */
export const AI_ACT_SPOKEN = {
  fr: 'Je suis un conseiller virtuel Callastral, et ma voix est générée par intelligence artificielle.',
  en: 'I am a Callastral virtual advisor, and my voice is generated by artificial intelligence.',
  es: 'Soy un consejero virtual de Callastral y mi voz está generada por inteligencia artificial.',
  de: 'Ich bin ein virtueller Callastral-Berater, und meine Stimme wird von künstlicher Intelligenz erzeugt.',
  it: 'Sono un consulente virtuale Callastral e la mia voce è generata dall’intelligenza artificiale.',
} as const;

export const AI_ACT_SPOKEN_FEMININE = {
  fr: 'Je suis une conseillère virtuelle Callastral, et ma voix est générée par intelligence artificielle.',
  en: 'I am a Callastral virtual advisor, and my voice is generated by artificial intelligence.',
  es: 'Soy una consejera virtual de Callastral y mi voz está generada por inteligencia artificial.',
  de: 'Ich bin eine virtuelle Callastral-Beraterin, und meine Stimme wird von künstlicher Intelligenz erzeugt.',
  it: 'Sono una consulente virtuale Callastral e la mia voce è generata dall’intelligenza artificiale.',
} as const;
